kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: greeting
  image: alpine
  commands:
  - ${DRONE_BRANCH}
  - ${DRONE_REPO_BRANCH}
  - ${DRONE_BRANCH##v}
  - ${DRONE_REPO_BRANCH##v}
  - ${DRONE_TARGET_BRANCH}
